package ai

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"net/http"
	"strings"
	"time"

	githubapi "github.com/RDX463/github-work-summary/internal/github"
	"github.com/RDX463/github-work-summary/internal/summary"
)

const (
	anthropicAPIVersion = "2023-06-01"
	anthropicURL        = "https://api.anthropic.com/v1/messages"
)

// AnthropicProvider implements the Provider interface using Anthropic's Messages API.
type AnthropicProvider struct {
	apiKey string
	model  string
}

type anthropicRequest struct {
	Model     string             `json:"model"`
	MaxTokens int                `json:"max_tokens"`
	Messages  []anthropicMessage `json:"messages"`
}

type anthropicMessage struct {
	Role    string `json:"role"`
	Content string `json:"content"`
}

type anthropicResponse struct {
	Content []struct {
		Text string `json:"text"`
	} `json:"content"`
	Error struct {
		Message string `json:"message"`
	} `json:"error"`
}

// NewAnthropicProvider creates a new Anthropic-backed AI provider.
func NewAnthropicProvider(apiKey string) *AnthropicProvider {
	return &AnthropicProvider{
		apiKey: apiKey,
		model:  "claude-3-5-sonnet-20240620", // Default to sonnet for highest quality
	}
}

// Summarize generates a summary using Claude.
func (p *AnthropicProvider) Summarize(ctx context.Context, report summary.Report) (string, error) {
	prompt := BuildReportPrompt(report)
	return p.GenerateRaw(ctx, prompt)
}

// GeneratePRDescription drafts a PR body via Claude.
func (p *AnthropicProvider) GeneratePRDescription(ctx context.Context, branchName string, commits []githubapi.Commit) (string, error) {
	prompt := BuildPRPrompt(branchName, commits)
	return p.GenerateRaw(ctx, prompt)
}

// GeneratePRTitle drafts a PR title via Claude.
func (p *AnthropicProvider) GeneratePRTitle(ctx context.Context, branchName string, commits []githubapi.Commit) (string, error) {
	prompt := BuildPRTitlePrompt(branchName, commits)
	return p.GenerateRaw(ctx, prompt)
}

// GeneratePRIntelligence performs a risk assessment and suggests labels using Claude.
func (p *AnthropicProvider) GeneratePRIntelligence(ctx context.Context, commits []githubapi.Commit) (PRIntelligence, error) {
	prompt := BuildPRIntelligencePrompt(commits)
	raw, err := p.GenerateRaw(ctx, prompt)
	if err != nil {
		return PRIntelligence{}, err
	}

	// Clean JSON if the model wrapped it in markdown
	raw = strings.TrimPrefix(raw, "```json")
	raw = strings.TrimPrefix(raw, "```")
	raw = strings.TrimSuffix(raw, "```")
	raw = strings.TrimSpace(raw)

	var intel PRIntelligence
	if err := json.Unmarshal([]byte(raw), &intel); err != nil {
		return PRIntelligence{}, fmt.Errorf("failed to parse PR intelligence JSON: %w", err)
	}

	return intel, nil
}

func (p *AnthropicProvider) GenerateRaw(ctx context.Context, prompt string) (string, error) {
	reqBody := anthropicRequest{
		Model:     p.model,
		MaxTokens: 1024,
		Messages: []anthropicMessage{
			{Role: "user", Content: prompt},
		},
	}

	jsonData, err := json.Marshal(reqBody)
	if err != nil {
		return "", err
	}

	req, err := http.NewRequestWithContext(ctx, http.MethodPost, anthropicURL, bytes.NewBuffer(jsonData))
	if err != nil {
		return "", err
	}

	req.Header.Set("Content-Type", "application/json")
	req.Header.Set("x-api-key", p.apiKey)
	req.Header.Set("anthropic-version", anthropicAPIVersion)

	client := &http.Client{Timeout: 30 * time.Second}
	resp, err := client.Do(req)
	if err != nil {
		return "", fmt.Errorf("claude request failed: %w", err)
	}
	defer resp.Body.Close()

	var result anthropicResponse
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return "", err
	}

	if result.Error.Message != "" {
		return "", fmt.Errorf("claude error: %s", result.Error.Message)
	}

	if len(result.Content) == 0 {
		return "", fmt.Errorf("no content generated by claude")
	}

	return result.Content[0].Text, nil
}

// GenerateTrendAnalysis summarizes activity over range using Anthropic.
func (p *AnthropicProvider) GenerateTrendAnalysis(ctx context.Context, report summary.Report) (string, error) {
	prompt := BuildTrendPrompt(report)
	return p.GenerateRaw(ctx, prompt)
}

// SummarizeWithPersona generates a summary using Claude tailored to a persona.
func (p *AnthropicProvider) SummarizeWithPersona(ctx context.Context, report summary.Report, persona string) (string, error) {
	prompt := getPromptForPersona(report, persona)
	return p.GenerateRaw(ctx, prompt)
}

// Name returns the provider name.
func (p *AnthropicProvider) Name() string {
	return "anthropic"
}
