package ai

import (
	"context"
	"encoding/json"
	"fmt"
	"strings"

	githubapi "github.com/RDX463/github-work-summary/internal/github"
	"github.com/RDX463/github-work-summary/internal/summary"
	"google.golang.org/genai"
)

// GeminiProvider implements the Provider interface using Google's GenAI SDK.
type GeminiProvider struct {
	client *genai.Client
	model  string
}

// NewGeminiProvider creates a new Gemini-backed AI provider.
func NewGeminiProvider(ctx context.Context, apiKey string) (*GeminiProvider, error) {
	client, err := genai.NewClient(ctx, &genai.ClientConfig{
		APIKey:  apiKey,
		Backend: genai.BackendGeminiAPI,
	})
	if err != nil {
		return nil, err
	}
	return &GeminiProvider{
		client: client,
		model:  "gemini-2.0-flash", // High performance stable model
	}, nil
}

// Summarize generates a summary using Gemini.
func (p *GeminiProvider) Summarize(ctx context.Context, report summary.Report) (string, error) {
	prompt := BuildReportPrompt(report)

	result, err := p.client.Models.GenerateContent(
		ctx,
		p.model,
		[]*genai.Content{{Parts: []*genai.Part{{Text: prompt}}}},
		nil,
	)
	if err != nil {
		return "", fmt.Errorf("gemini generation failed: %w", err)
	}

	if len(result.Candidates) == 0 || len(result.Candidates[0].Content.Parts) == 0 {
		return "", fmt.Errorf("no summary generated by gemini")
	}

	return result.Candidates[0].Content.Parts[0].Text, nil
}

// GeneratePRDescription drafts a PR body via Gemini.
func (p *GeminiProvider) GeneratePRDescription(ctx context.Context, branchName string, commits []githubapi.Commit) (string, error) {
	prompt := BuildPRPrompt(branchName, commits)
	return p.generateRaw(ctx, prompt)
}

// GeneratePRTitle drafts a PR title via Gemini.
func (p *GeminiProvider) GeneratePRTitle(ctx context.Context, branchName string, commits []githubapi.Commit) (string, error) {
	prompt := BuildPRTitlePrompt(branchName, commits)
	return p.generateRaw(ctx, prompt)
}

// GeneratePRIntelligence performs a risk assessment and suggests labels using Gemini.
func (p *GeminiProvider) GeneratePRIntelligence(ctx context.Context, commits []githubapi.Commit) (PRIntelligence, error) {
	prompt := BuildPRIntelligencePrompt(commits)
	raw, err := p.generateRaw(ctx, prompt)
	if err != nil {
		return PRIntelligence{}, err
	}

	// Clean JSON if the model wrapped it in markdown
	raw = strings.TrimPrefix(raw, "```json")
	raw = strings.TrimPrefix(raw, "```")
	raw = strings.TrimSuffix(raw, "```")
	raw = strings.TrimSpace(raw)

	var intel PRIntelligence
	if err := json.Unmarshal([]byte(raw), &intel); err != nil {
		return PRIntelligence{}, fmt.Errorf("failed to parse PR intelligence JSON: %w", err)
	}

	return intel, nil
}

func (p *GeminiProvider) generateRaw(ctx context.Context, prompt string) (string, error) {
	result, err := p.client.Models.GenerateContent(ctx, p.model, []*genai.Content{{Parts: []*genai.Part{{Text: prompt}}}}, nil)
	if err != nil {
		return "", err
	}
	if len(result.Candidates) == 0 || len(result.Candidates[0].Content.Parts) == 0 {
		return "", fmt.Errorf("gemini generated no content")
	}
	return result.Candidates[0].Content.Parts[0].Text, nil
}

// GenerateTrendAnalysis summarizes activity over range using Gemini.
func (p *GeminiProvider) GenerateTrendAnalysis(ctx context.Context, report summary.Report) (string, error) {
	prompt := BuildTrendPrompt(report)
	return p.generateRaw(ctx, prompt)
}

// SummarizeWithPersona generates a summary using Gemini tailored to a persona.
func (p *GeminiProvider) SummarizeWithPersona(ctx context.Context, report summary.Report, persona string) (string, error) {
	prompt := getPromptForPersona(report, persona)
	return p.generateRaw(ctx, prompt)
}

// Name returns the provider name.
func (p *GeminiProvider) Name() string {
	return "gemini"
}
